image: python:3.6.4-stretch

pages:
  script:
  - pip install sphinx numpy sphinx_rtd_theme versioneer sqlalchemy
  - python setup.py install
  - rm -rf docs/source && sphinx-apidoc -e -f -o docs/source/ pynmet/
  - cd docs/ && make html && cd ../
  - mv docs/_build/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master

pypi:
    stage: release
    cache: {}
    script:
        - pip install -U twine
        - python setup.py sdist
        - twine upload dist/*
    only:
        - tags